Update README.md
swiftdevelopersitalia/Regolamento pull request #1
Opened 2023-05-17 21:25 UTC by swiftdevelopersitalia

2023-05-18 03:50 UTC, giuseppesorce requested changes
Aggiungiamo il divieto di mettere lo stesso annuncio piu' volte con un limite temporale di 3 mesi ?

2023-05-18 03:50 UTC, giuseppesorce commented on README.md
> +
In ADI mi manca, ma lo aggiungo a breve la regola , che non si possono inserire annunci identici nel breve tempo. e' successo che hanno inserito lo stesso annuncio piu' volte. Metterei almeno 3 mesi oppure se si vuole inserire una nuova posizione occorre cambiare la RAL e/o esperienza, annuncio ricerca junior ma puoi inserire l' annuncio di middle.. e dopo 3 mesi puoi inserire lo stesso annuncio. Ho detto 3 mesi come tempo accettabile ma pensaci anche tu

2023-05-18 17:03 UTC, giuseppesorce approved these changes

2023-05-19 07:40 UTC, codingspark approved these changes

2023-05-19 07:42 UTC, merged